package trabalho.cg;

import java.awt.Color;
import java.awt.FlowLayout;
import javax.media.opengl.GLCanvas;
import javax.media.opengl.GLCapabilities;
import javax.swing.JColorChooser;

/**
 * Janela da interface gráfica.
 * 
 */
public class Janela extends javax.swing.JFrame{

    Renderer renderer;

    public Janela(){
        initComponents();
        
        PreePol pp = new PreePol();
       
        //Acelera o rendering
        GLCapabilities caps = new GLCapabilities();
        caps.setDoubleBuffered(true);
        caps.setHardwareAccelerated(true);
        
        //cria o painel e adiciona um ouvinte GLEventListener
        GLCanvas canvas = new GLCanvas();
        canvas.setSize(500, 500);
        renderer = new Renderer(canvas, pp);
        canvas.addGLEventListener(renderer);
        canvas.addMouseListener(renderer);
        
        //Insere canvas na janela
        FlowLayout layout = new FlowLayout();
        painelOGL.setLayout(layout);
        painelOGL.add(canvas);
        
        //Configurações adicionais
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelOGL = new javax.swing.JPanel();
        cor = new javax.swing.JButton();
        preencher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trabalho de Computação Gráfica");
        setMinimumSize(new java.awt.Dimension(550, 640));

        painelOGL.setPreferredSize(new java.awt.Dimension(507, 529));

        javax.swing.GroupLayout painelOGLLayout = new javax.swing.GroupLayout(painelOGL);
        painelOGL.setLayout(painelOGLLayout);
        painelOGLLayout.setHorizontalGroup(
            painelOGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );
        painelOGLLayout.setVerticalGroup(
            painelOGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );

        cor.setText("Cor");
        cor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corActionPerformed(evt);
            }
        });

        preencher.setText("Preencher");
        preencher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preencherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelOGL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(preencher, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cor, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelOGL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(preencher, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(cor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ao clicar no botão "Preencher"
     */
    private void preencherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preencherActionPerformed
        if(renderer.preencher()){
            preencher.setText("Apagar");
        }else{
            preencher.setText("Preencher");
        }
    }//GEN-LAST:event_preencherActionPerformed

    /**
     * Ao clicar no botão "Cor" 
     */
    private void corActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corActionPerformed
        Color cor = JColorChooser.showDialog(null, "Cor", Color.RED);
        if(cor !=null){
            renderer.setCor(cor.getRed(), cor.getGreen(), cor.getBlue());
        }
    }//GEN-LAST:event_corActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cor;
    private javax.swing.JPanel painelOGL;
    private javax.swing.JButton preencher;
    // End of variables declaration//GEN-END:variables
}
